// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Команда для заполнения БД тестовыми данными (запуск: npx prisma db seed)
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    // DIRECT_URL (порт 5432, без pgbouncer) нужен для CLI-команд (migrate, db push)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
